services:

  frontend:
    container_name: nmatute-frontend
    build:
      context: ./frontend
      args:
        SERVER_URL: "http://nmatute-backend"
        PUBLIC_MAILTO: contact@nmatute.com #optional
    depends_on:
      - backend
    volumes:
      - type: volume
        source: frontend-data
        target: /app/frontend
        read_only: true
    networks:
      - nginx-subdomain-proxy

  backend:
    container_name: nmatute-backend
    build:
      context: ./backend
    volumes:
      - type: volume
        source: backend-data
        target: /app/backend
        read_only: true
      - type: bind
        source: /docker-data/web-nmatute
        target: /app/data
        read_only: true
    networks:
      - nginx-subdomain-proxy

volumes:
  frontend-data:
  backend-data: