networks:
  traefik:
    external: true
    name: traefik
  web-nmatute:
    internal: true
    name: web-nmatute

volumes:
  backend-data:

services:
  frontend:
    container_name: nmatute-frontend
    restart: always
    expose: ["3000"]
    build:
      context: ./frontend
      args:
        BACKEND_ORIGIN: "http://nmatute-backend"
        PUBLIC_MAILTO: contact@nmatute.com #optional
    depends_on:
      - backend
    networks:
      - traefik
      - web-nmatute
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.nmatute.rule=Host(`nmatute.com`)"
      - "traefik.http.routers.nmatute.entrypoints=websecure"
      - "traefik.http.routers.nmatute.tls=true"
      - "traefik.http.services.nmatute.loadbalancer.server.port=3000"

  backend:
    container_name: nmatute-backend
    restart: always
    expose: ["80"]
    build:
      context: ./backend
    volumes:
      - type: bind
        source: /docker-data/web-nmatute
        target: /app/data
        read_only: true
    networks:
      - web-nmatute
