services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./frontend/nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - frontend
    networks:
      - web

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        BACKEND_ORIGIN: "http://backend"
        PUBLIC_MAILTO: contact@nmatute.com #optional
    depends_on:
      - backend
    networks:
      - web

  backend:
    build:
      context: ./backend
    volumes:
      - type: bind
        source: C:/workdir/nmatute.com/web-nmatute-test
        target: /app/data
        read_only: true
    networks:
      - web
        

networks:
  web:
    internal: true
