networks:
  traefik:
    external: true
    name: traefik
  web-nmatute:
    internal: true
    name: web-nmatute

volumes:
  backend-data:

services:
  frontend:
    container_name: nmatute-frontend
    restart: always
    expose: ["8080"]
    build:
      context: ./frontend
      args:
        SERVER_URL: "/api"
        PUBLIC_MAILTO: contact@nmatute.com #optional
    depends_on:
      - backend
    networks:
      - traefik
      - web-nmatute
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.nmatute.rule=(Host(`nmatute.com`) || Host(`www.nmatute.com`))
      - traefik.http.routers.nmatute.entrypoints=websecure
      - traefik.http.routers.nmatute.tls=true
      - traefik.http.services.nmatute.loadbalancer.server.port=8080

  backend:
    container_name: nmatute-backend
    restart: always
    expose: ["8000"]
    build:
      context: ./backend
      args:
        PORT: 8000
    volumes:
      - type: bind
        source: /docker-data/web-nmatute
        target: /app/data
        read_only: true
    networks:
      - traefik
      - web-nmatute
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.nmatute-api.rule=(Host(`nmatute.com`) || Host(`www.nmatute.com`)) && PathPrefix(`/api`)
      - traefik.http.routers.nmatute-api.priority=1000
      - traefik.http.routers.nmatute-api.entrypoints=websecure
      - traefik.http.routers.nmatute-api.tls=true
      - traefik.http.services.nmatute-api.loadbalancer.server.port=8000
      # strip /api before proxying to the backend
      - traefik.http.middlewares.nmatute-strip.stripprefix.prefixes=/api
      - traefik.http.routers.nmatute-api.middlewares=nmatute-strip
