services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./frontend/nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
    networks:
      - web

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        SERVER_URL: "http://backend"
        PUBLIC_MAILTO: contact@nmatute.com #optional
    depends_on:
      - backend
    volumes:
      - type: volume
        source: frontend-data
        target: /app/frontend
        read_only: true
    networks:
      - web

  backend:
    build:
      context: ./backend
    environment:
      ORIGIN: "localhost"
    volumes:
      - type: volume
        source: backend-data
        target: /app/backend
        read_only: true
      - type: bind
        source: C:/workdir/nmatute.com/web-nmatute-test
        target: /app/data
        read_only: true
    networks:
      - web
        

networks:
  web:

volumes:
  frontend-data:
  backend-data: