version: '3'
services:
  frontend:
    build:
      context: ./frontend
    environment:
      PUBLIC_SERVER_URL: "/api"
    ports:
      - "443:443"
    depends_on:
      - backend
    volumes:
      - type: volume
        source: frontend-data
        target: /app/frontend
        read_only: true
    networks:
      - web

  backend:
    build:
      context: ./backend
    environment:
      - ORIGIN=${ORIGIN}
      - MAIL_ACCOUNT=${MAIL_ACCOUNT}
      - MAIL_PASS=${MAIL_PASS}
      - MAIL_SIGNATURE=${MAIL_SIGNATURE}
    volumes:
      - type: volume
        source: backend-data
        target: /app/backend
        read_only: true
      - type: bind
        source: /docker-data/web-nmatute
        target: /app/data
        read_only: true
    networks:
      - web
        

networks:
  web:

volumes:
  frontend-data:
  backend-data: