services:
  backend:
    build:
      context: .
    image: web-nmatute-backend:latest
    environment:
      PORT: 4000
      ORIGIN: "*"
    ports:
      - 4000:4000
    volumes:
      - type: volume
        source: backend-data
        target: /app/backend
        read_only: true
      - type: bind
        source: C:/workdir/tests/web-nmatute
        target: /app/data
        read_only: true
    networks:
      - web

networks:
  web:

volumes:
  backend-data:
