services:
  frontend:
    build:
      context: .
      args:
        BACKEND_URL: http://localhost:4000
        MAILTO: contact@nmatute.com
    image: web-nmatute-frontend:latest
    ports:
      - 80:80
    volumes:
      - type: volume
        source: frontend-data
        target: /app/frontend
        read_only: true

volumes:
  frontend-data:
