// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Content struct {
	Name  *string   `json:"name,omitempty"`
	Role  *string   `json:"role,omitempty"`
	Start *string   `json:"start,omitempty"`
	End   *string   `json:"end,omitempty"`
	Tasks []*string `json:"tasks,omitempty"`
	Title *string   `json:"title,omitempty"`
	URL   *string   `json:"url,omitempty"`
}

type DataSection struct {
	Name  string  `json:"name"`
	Items []*Item `json:"items"`
}

type Item struct {
	Keywords []*string `json:"keywords,omitempty"`
	Content  *Content  `json:"content,omitempty"`
}

type Query struct {
}
