package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"

	"nmatute.com/web-nmatute-backend/graph/model"
)

var DataSections []model.DataSection

func init() {
	DataSections = make([]model.DataSection, 0)
}

// GetData is the resolver for the getData field.
func (r *queryResolver) GetData(ctx context.Context, name string) (*model.DataSection, error) {
	for _, section := range DataSections {
		if section.Name == name {
			return &section, nil
		}
	}
	return nil, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
