name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      # Step 2: Install dependencies
      - name: Install ssh
        run: sudo apt update && sudo apt install -y openssh-client

      # Step 3: Upload code to VPS using FTPS    
      - name: 📂 Sync files
        env:
          FTP_HOST: 
          FTP_USER: 
          FTP_PASS: 
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          port: 990
          protocol: ftps
          server-dir: /home/silly/web-nmatite
          dangerous-clean-slate: true

      # Step 4: Trigger docker-compose build via SSH
      - name: Trigger docker-compose build
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
            echo "$SSH_KEY" > private_key.pem
            chmod 600 private_key.pem
            ssh -i private_key.pem -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
                cd /home/silly/web-nmatute && docker-compose up --build --force-recreate
            "
