name: deploy
on:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout (shallow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Upload files via SCP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          # Explicit list beats "." — tailor to what build.sh needs:
          source: "backend,frontend,docker-compose.yaml,build.sh"
          target: "/home/${{ secrets.SSH_USER }}/deploys/${{ vars.DIRECTORY_NAME }}"
          overwrite: true

      - name: Run remote build
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          command_timeout: 30m
          script: |
            set -euo pipefail
            cd /home/${{ secrets.SSH_USER }}/deploys/${{ vars.DIRECTORY_NAME }}
            chmod +x build.sh
            ./build.sh

      - name: Send success email
        if: ${{ success() }}
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: 587
          secure: false
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "✅ CI succeeded on ${{ github.repository }}@${{ github.ref_name }}"
          to: ${{ secrets.DESTINATION_EMAIL }}
          from: ${{ secrets.SENDER_EMAIL }}
          body: "Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"