name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout source code
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install lftp and ssh
        run: sudo apt-get update && sudo apt-get install -y lftp openssh-client

      # Step 3: Upload code to VPS using FTPS
      - name: Upload code via FTP
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
        run: |
          lftp -d -u "$FTP_USER,$FTP_PASS" -e "
              set ftp:ssl-allow no; # Disable SSL
              mirror --reverse --verbose ./ /home/silly/web-nmatute/;
              quit
          " ftp://$FTP_HOST

      # Step 4: Trigger docker-compose build via SSH
      - name: Trigger docker-compose build
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
            echo "$SSH_KEY" > private_key.pem
            chmod 600 private_key.pem
            ssh -i private_key.pem -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
                cd /home/silly/web-nmatute && docker-compose up --build --force-recreate
            "
