name: push

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt update && sudo apt install -y sshpass

      # Step 3: Upload code to VPS using FTPS    
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          port: 21
          protocol: ftps
          server-dir: ./uploads/web-nmatute/
          dangerous-clean-slate: true

